# Generated by Django 5.1 on 2024-09-12 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Attribut',
            },
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prix_ht',
            new_name='price_ht',
        ),
        migrations.AddField(
            model_name='product',
            name='price_ttc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Prix unitaire TTC'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Offline'), (1, 'Online'), (2, 'Out of stock')], default=0),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.product'),
        ),
        migrations.AlterField(
            model_name='status',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Position')),
                ('product_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.productattribute', verbose_name='Unité')),
            ],
            options={
                'verbose_name': 'Valeur attribut',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='productitem',
            name='attributes',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_item', to='monapp.productattributevalue'),
        ),
    ]
