# Generated by Django 5.1 on 2024-10-10 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0003_fournisseur_product_stock_prixproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prixproduct',
            options={'verbose_name': 'Referencement Fournisseur'},
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fournisseur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.fournisseur', verbose_name='Fournisseur')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monapp.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Order',
            },
        ),
    ]
